### ISSUE TITLE
Fail to add new tags

### ISSUE THREAD

**Issue by Sereinme** [Future-Scholars/paperlib-ai-summary-extension#2]
Adding new tags failed when ai tag it with already some tags, only thing I can do to fix this is to delete all existing tags, create new tags and ai re-tag it.
<img width="243" alt="截屏2024-05-31 21 01 42" src="https://github.com/Future-Scholars/paperlib-ai-summary-extension/assets/73818129/1a10b233-d68c-482c-a9d9-6ee05d5ba35d">

**Comment by GeoffreyChen777** [comment]
That's expected.

AI-tag assists you in tagging a paper, however, if one paper already has some tags, it usually means the user has some preferred tags assigned. In this case, AI-tag will do nothing.
