### ISSUE TITLE
How to set this plugin?

### ISSUE THREAD

**Issue by WissenY** [Future-Scholars/paperlib-ai-summary-extension#3]
Does this plugin need api keys to try all the functions provided by this plugin? 

I have tried to use this amazing plugin to assist my research under the great power of AI such as tagging the articles or summarizing long papers. But it still not works when I set a correct IP in US. Here I'm curious about whether API key is necessary to use this plugin.

![CleanShot 2024-09-24 at 17 49 02@2x](https://github.com/user-attachments/assets/3aa7c209-f88f-466c-96a6-28a1f75b50c7)

**Comment by GeoffreyChen777** [comment]
Yes, you need to provide your API key.
<img width="416" alt="image" src="https://github.com/user-attachments/assets/0b2a067e-860e-431d-9f8a-86351a2f9e72">
